### ISSUE TITLE
DiffAugment-biggan-imagenet missing 'mock' dependency

### ISSUE THREAD

**Issue by gwern** [mit-han-lab/data-efficient-gans#32]
I've started trying to run the ImageNet code on my TPU pod to validate that it works before trying at higher resolutions with my anime datasets, and the requirements appears to be missing the `mock` dependency, so it currently has to be pip-installed separately:

```
cd ./data-efficient-gans/DiffAugment-biggan-imagenet/
pip install -e .
pip install mock
```

---

On a side note, I am curious if you guys have any thoughts about why this fork works while the original compare\_gan appears to not match the BigGAN numbers? Your paper clearly indicates that you trained [the baseline BigGAN 3 times](https://arxiv.org/pdf/2006.10738.pdf#page=6) and got good FID/IS numbers (which are not copied from the original BigGAN paper), but our ImageNet runs with compare\_gan never worked well. I copied over all the original files to look at the diff, and the only thing that seems meaningfully different is that all of your runs, data-augmented or not, [use image-zooming](https://pastebin.com/qR2dK7xV) rather than the original cropping code. I can't imagine how that could fix compare\_gan but I also don't see what else could be the difference.

**Comment by zsyzzsoft** [comment]
You are right. We state clearly in the paper in Appendix A.1 that "Second, it processes the raw images into 128×128 resolution
with random scaling and random cropping. Since we find that random cropping leads to a worse
IS, we process the raw images with random scaling and center cropping instead. We additionally
augment the images with random horizontal flips, yielding the best re-implementation of BigGAN
to our knowledge. " This does make difference.
